import reflex as rx

from components.navbar import navbar
from full_stack_using_reflex.state import ReviewerState


def posts() -> rx.Component:
    return rx.box(
        rx.container(
            rx.vstack(
                navbar(),
                rx.vstack(
            rx.heading("Review Code", size="7", color="#f8fafc", margin_top="0.75rem"),
            rx.text(
                "Paste code in any supported language and run a full analysis.",
                color="#cbd5e1",
            ),
            rx.hstack(
                rx.text("Language", color="#93c5fd", font_weight="600"),
                rx.select(
                    ReviewerState.available_languages,
                    value=ReviewerState.selected_language,
                    on_change=ReviewerState.update_language,
                    width="220px",
                    color="#e2e8f0",
                    background="#0b1220",
                    border="1px solid #334155",
                ),
                spacing="3",
                align="center",
            ),
            rx.text_area(
                value=ReviewerState.code_input,
                on_change=ReviewerState.update_code_input,
                placeholder="Paste your source code here...",
                min_height="280px",
                width="100%",
                background="#0b1220",
                border="1px solid #334155",
                color="#e2e8f0",
            ),
            rx.hstack(
                rx.button(
                    "Analyze Code",
                    on_click=ReviewerState.analyze,
                    color_scheme="cyan",
                    _hover={"transform": "translateY(-2px)"},
                ),
                rx.button(
                    "Load Demo",
                    on_click=ReviewerState.load_demo,
                    variant="outline",
                    color_scheme="cyan",
                ),
                rx.button(
                    "Download PDF Report",
                    on_click=ReviewerState.download_pdf_report,
                    variant="outline",
                    color_scheme="blue",
                ),
                spacing="3",
            ),
            rx.cond(
                ReviewerState.error_message != "",
                rx.box(
                    rx.text(ReviewerState.error_message, color="#fecaca"),
                    width="100%",
                    border="1px solid #7f1d1d",
                    background="#450a0a",
                    border_radius="10px",
                    padding="0.7rem",
                ),
            ),
            rx.box(
                rx.hstack(
                    rx.box(
                        rx.text("Quality Grade", color="#94a3b8", font_size="0.9rem"),
                        rx.heading(ReviewerState.quality_grade, size="6"),
                        width="100%",
                    ),
                    rx.box(
                        rx.text("Issues Found", color="#94a3b8", font_size="0.9rem"),
                        rx.heading(ReviewerState.issues_count.to_string(), size="6"),
                        width="100%",
                    ),
                    spacing="6",
                    width="100%",
                ),
                width="100%",
                border="1px solid #334155",
                border_radius="12px",
                background="#0b1220",
                padding="1rem",
            ),
            rx.cond(
                ReviewerState.ai_fallback,
                rx.text(
                    "AI response fallback was used for this run.",
                    color="#facc15",
                    font_size="0.95rem",
                ),
            ),
            rx.box(
                rx.heading("Analysis Summary", size="5", margin_bottom="0.5rem"),
                rx.text(ReviewerState.analysis_summary, color="#cbd5e1", white_space="pre-wrap"),
                width="100%",
                border="1px solid #334155",
                border_radius="12px",
                background="#0b1220",
                padding="1rem",
            ),
            rx.box(
                rx.heading("Side-by-Side Comparison", size="5", margin_bottom="0.75rem"),
                rx.grid(
                    rx.box(
                        rx.text("Original", color="#cbd5e1", font_weight="700", margin_bottom="0.5rem"),
                        rx.text(
                            ReviewerState.original_code_with_lines,
                            white_space="pre-wrap",
                            font_family="Consolas, monospace",
                            font_size="0.9rem",
                            color="#fecaca",
                        ),
                        width="100%",
                        min_height="240px",
                        max_height="360px",
                        overflow="auto",
                        border="1px solid #3f3f46",
                        border_radius="10px",
                        background="#111827",
                        padding="0.75rem",
                    ),
                    rx.box(
                        rx.text("Improved", color="#cbd5e1", font_weight="700", margin_bottom="0.5rem"),
                        rx.text(
                            ReviewerState.improved_code_with_lines,
                            white_space="pre-wrap",
                            font_family="Consolas, monospace",
                            font_size="0.9rem",
                            color="#bbf7d0",
                        ),
                        width="100%",
                        min_height="240px",
                        max_height="360px",
                        overflow="auto",
                        border="1px solid #3f3f46",
                        border_radius="10px",
                        background="#111827",
                        padding="0.75rem",
                    ),
                    columns={"base": "1", "lg": "2"},
                    width="100%",
                    spacing="4",
                    align_items="start",
                ),
                width="100%",
                border="1px solid #334155",
                border_radius="12px",
                background="#0b1220",
                padding="1rem",
            ),
            rx.box(
                rx.heading("Issues Found", size="5", margin_bottom="0.5rem"),
                rx.vstack(
                    rx.foreach(
                        ReviewerState.issues_found,
                        lambda issue: rx.text(issue, color="#e2e8f0", width="100%"),
                    ),
                    spacing="2",
                    align="start",
                    width="100%",
                ),
                width="100%",
                border="1px solid #334155",
                border_radius="12px",
                background="#0b1220",
                padding="1rem",
            ),
            rx.box(
                rx.heading("Improved Code", size="5", margin_bottom="0.5rem"),
                rx.text(
                    ReviewerState.improved_code,
                    white_space="pre-wrap",
                    font_family="Consolas, monospace",
                    color="#bae6fd",
                ),
                width="100%",
                border="1px solid #334155",
                border_radius="12px",
                background="#0b1220",
                padding="1rem",
            ),
            rx.box(
                rx.heading("Static Analysis", size="5", margin_bottom="0.5rem"),
                rx.text("Unused Imports", color="#93c5fd", font_weight="600"),
                rx.foreach(
                    ReviewerState.unused_imports,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                rx.text("Unused Functions", color="#93c5fd", font_weight="600", margin_top="0.75rem"),
                rx.foreach(
                    ReviewerState.unused_functions,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                rx.text("Unused Variables", color="#93c5fd", font_weight="600", margin_top="0.75rem"),
                rx.foreach(
                    ReviewerState.unused_variables,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                rx.text("Style Violations", color="#93c5fd", font_weight="600", margin_top="0.75rem"),
                rx.foreach(
                    ReviewerState.style_violations,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                rx.text("External Linter Tool Status", color="#93c5fd", font_weight="600", margin_top="0.75rem"),
                rx.foreach(
                    ReviewerState.external_linter_tool_status,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                rx.text("External Linter Findings", color="#93c5fd", font_weight="600", margin_top="0.75rem"),
                rx.foreach(
                    ReviewerState.external_linter_violations,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                width="100%",
                border="1px solid #334155",
                border_radius="12px",
                background="#0b1220",
                padding="1rem",
            ),
            rx.box(
                rx.heading("Variable Context (code_visitor)", size="5", margin_bottom="0.5rem"),
                rx.text("Created Variables", color="#93c5fd", font_weight="600"),
                rx.foreach(
                    ReviewerState.created_variables,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                rx.text("Used Variables", color="#93c5fd", font_weight="600", margin_top="0.75rem"),
                rx.foreach(
                    ReviewerState.used_variables,
                    lambda item: rx.text(item, color="#e2e8f0", width="100%"),
                ),
                width="100%",
                border="1px solid #334155",
                border_radius="12px",
                background="#0b1220",
                padding="1rem",
            ),
            spacing="4",
            align="start",
            width="100%",
                ),
                width="100%",
                max_width="1100px",
                margin="0 auto",
                spacing="4",
                align="start",
            ),
            max_width="1160px",
            width="100%",
            padding_y="1.6rem",
            padding_x={"base": "1rem", "md": "1.3rem"},
        ),
        width="100%",
        display="flex",
        justify_content="center",
    )
